[{
        id: 75,
        title: "Pro - 30% הנחה + POGO מבחן חינם! 🏆🔥",
        description: "30% הנחה על מסלול Pro ב-MFFU (ללא תוסף מעבר מבחן ביום אחד). עוברים את המבחן ומקבלים קופון POGO למבחן נוסף ב-100% הנחה - ללא הגבלת שימושים!",
        company: "MFFU",
        discount: "30% + POGO",
        code: "PAYLESS",
        validUntil: "1 במאי 2026 בשעה 23:00",
        countdown: new Date("2026-05-01T20:00:00Z"),
        isHot: !0,
        isExclusive: !0,
        features: ["30% הנחה על מסלול Pro", "ללא תוסף מעבר מבחן ביום אחד", "POGO: עוברים מבחן = מבחן נוסף ב-100% הנחה", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 120,
        title: "Rapid 50K - 25% הנחה - כ-$118! 🔥",
        description: "25% הנחה (במקום 20%) על תיק Rapid 50K בלבד - חיסכון של $39! המחיר לאחר הנחה כ-$118. עד 6.6.26 בשעה 07:00 שעון ישראל.",
        company: "MFFU",
        discount: "25% הנחה",
        code: "PAYLESS",
        validUntil: "6 ביוני 2026 בשעה 07:00 (שעון ישראל)",
        countdown: new Date("2026-06-06T04:00:00Z"),
        isHot: !0,
        isExclusive: !0,
        features: ["25% הנחה במקום 20% - חיסכון של $39", "תיק Rapid 50K בלבד", "מחיר לאחר הנחה: כ-$118", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 76,
        title: "מבצע השקה Premium - 25% הנחה! 💎🚀",
        description: "מבצע השקה לחגיגת מסלול Premium החדש של Alpha Futures - 25% הנחה על כל גדלי התיקים! ללא הגבלת שימושים.",
        company: "AlphaFutures",
        discount: "25% הנחה",
        code: "PAYLESS",
        validUntil: "8 במאי 2026 בסוף היום",
        countdown: new Date("2026-05-08T20:59:00Z"),
        isHot: !0,
        isExclusive: !0,
        features: ["25% הנחה על מסלול Premium", "מבצע השקה - לזמן מוגבל", "כל גדלי התיקים (50K, 100K, 150K)", "קוד PAYLESS"],
        affiliateLink: "https://app.alpha-futures.com/signup/PAYLESS/"
    }, {
        id: 108,
        title: "מבצע השקת ALPHA TRADER - 50% הנחה! 🚀",
        description: "מבצע השקה לפלטפורמת ALPHA TRADER החדשה של Alpha Futures - 50% הנחה ברכישה על כל פלטפורמות המסחר (לא רק ALPHA TRADER). 48 שעות בלבד!",
        company: "AlphaFutures",
        discount: "50% הנחה",
        code: "PAYLESS",
        validUntil: "22 במאי 2026 בשעה 10:00 (שעון ישראל)",
        countdown: new Date("2026-05-22T07:00:00Z"),
        isHot: !0,
        isExclusive: !0,
        features: ["50% הנחה ברכישה", "חל על כל פלטפורמות המסחר (לא רק ALPHA TRADER)", "48 שעות בלבד - החל מ-20.05.26 בשעה 10:00 שעון ישראל", "קוד PAYLESS"],
        affiliateLink: "https://app.alpha-futures.com/signup/PAYLESS/"
    }, {
        id: 109,
        title: "מבצע השקת ALPHA TRADER - 25% הנחה! 🚀",
        description: "מבצע השקה לפלטפורמת ALPHA TRADER החדשה של Alpha Futures - 25% הנחה ללא הגבלת שימושים על כל המסלולים והפלטפורמות בחברה.",
        company: "AlphaFutures",
        discount: "25% הנחה",
        code: "PAYLESS",
        validUntil: "31 במאי 2026 בחצות",
        countdown: new Date("2026-05-31T20:59:00Z"),
        isHot: !0,
        isExclusive: !0,
        features: ["25% הנחה על כל המסלולים והפלטפורמות", "ללא הגבלת שימושים", "קוד PAYLESS"],
        affiliateLink: "https://app.alpha-futures.com/signup/PAYLESS/"
    }, {
        id: 121,
        title: "חגיגת $70M משיכות - 25% הנחה! 🎉",
        description: "Alpha Futures חוגגים $70 מיליון דולר משיכות שאושרו עד כה - 25% הנחה על כל המסלולים והפלטפורמות בחברה. ללא הגבלת זמן!",
        company: "AlphaFutures",
        discount: "25% הנחה",
        code: "PAYLESS",
        validUntil: "ללא הגבלת זמן",
        isHot: !0,
        isExclusive: !0,
        features: ["25% הנחה על כל המסלולים והפלטפורמות", "חגיגת $70M משיכות שאושרו", "ללא הגבלת זמן - קוד PAYLESS"],
        affiliateLink: "https://app.alpha-futures.com/signup/PAYLESS/"
    }, {
        id: 105,
        title: "50% הנחה על כל סוגי התיקים! 🔥",
        description: "50% הנחה על כל מסלולי האתגר בלוסיד! מוגבל ל-2 שימושים בלבד.",
        company: "LucidTrading",
        discount: "50% הנחה",
        code: "PAYLESS",
        validUntil: "2 ביולי 2026 בחצות",
        countdown: new Date("2026-07-01T21:00:00Z"),
        usageLimit: "2 שימושים בלבד",
        isHot: !0,
        isExclusive: !0,
        features: ["50% הנחה על כל מסלולי האתגר", "חל על כל גדלי התיקים", "2 שימושים בלבד", "קוד PAYLESS"],
        affiliateLink: "https://lucidtrading.com/ref/PAYLESS/"
    }, {
        id: 106,
        title: "30% הנחה קבועה על כל התיקים",
        description: "30% הנחה קבועה על מסלולי האתגר בלוסיד - מבצע קבוע ללא הגבלת זמן, שנכנס לתוקף לאחר ניצול 2 השימושים של מבצע ה-50%.",
        company: "LucidTrading",
        discount: "30% הנחה",
        code: "PAYLESS",
        validUntil: "ללא הגבלת זמן",
        isExclusive: !0,
        features: ["30% הנחה קבועה על מסלולי האתגר", "מבצע קבוע ללא הגבלת זמן", "חל לאחר ניצול מבצע ה-50%", "קוד PAYLESS"],
        affiliateLink: "https://lucidtrading.com/ref/PAYLESS/"
    }, {
        id: 74,
        title: "Rapid - 32% הנחה על כל הגדלים! 🔥",
        description: "32% הנחה על כל גדלי התיקים במסלול Rapid (כולל 25K, 50K, 100K, 150K). 2 שימושים ללקוח, חידוש במחיר מלא.",
        company: "MFFU",
        discount: "32% הנחה",
        code: "PAYLESS",
        validUntil: "30 באפריל 2026",
        countdown: new Date("2026-05-01T00:00:00Z"),
        usageLimit: "2 שימושים ללקוח",
        isHot: !0,
        isExclusive: !0,
        features: ["32% הנחה על כל גדלי Rapid", "2 שימושים ללקוח", "חידוש במחיר מלא", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 63,
        title: "1+1 על Rapid - כל הגדלים! 🔥🔥",
        description: "עוברים את המבחן ומקבלים מבחן נוסף חינם מתנה! + 20% הנחה לחודש הראשון על כל גדלי התיקים במסלול Rapid",
        company: "MFFU",
        discount: "1+1",
        code: "PAYLESS",
        validUntil: "15 באפריל 2026 בשעה 17:00",
        countdown: new Date("2026-04-15T14:00:00Z"),
        isHot: !0,
        isExclusive: !0,
        features: ["1+1: עוברים מבחן = מבחן נוסף חינם!", "20% הנחה לחודש הראשון", "כל גדלי התיקים במסלול Rapid", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 29,
        title: "PRO מצטרפים חדשים 50% הנחה! 🔥",
        description: "50% הנחה חד פעמית לחודש הראשון למצטרפים חדשים - מסלול PRO ללא תוסף",
        company: "MFFU",
        discount: "50% הנחה",
        code: "PAYLESS",
        validUntil: "31 בדצמבר 07:00",
        countdown: new Date("2025-12-31T07:00:00"),
        usageLimit: "שימוש חד פעמי",
        isHot: !0,
        isExclusive: !0,
        features: ["50% הנחה למצטרפים חדשים", "שימוש חד פעמי בלבד", "לחודש הראשון בלבד", "מסלול PRO ללא תוסף"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 30,
        title: "PRO ללא תוסף 30% הנחה 🔥",
        description: "30% הנחה על תיקי PRO ללא תוסף - כל הגדלים, עד 3 שימושים",
        company: "MFFU",
        discount: "30% הנחה",
        code: "PAYLESS",
        validUntil: "ללא תוקף",
        usageLimit: "3 שימושים",
        isHot: !0,
        isExclusive: !0,
        features: ["30% הנחה על תיקי PRO", "ללא תוסף - כל הגדלים", "עד 3 שימושים", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 53,
        title: "Rapid 50K - 38% הנחה - $97 במקום $157! 🔥",
        description: "38% הנחה על מסלול Rapid 50K - לחודש הראשון בלבד, ללקוחות חדשים וקיימים!",
        company: "MFFU",
        discount: "38% הנחה",
        originalPrice: "$157",
        salePrice: "$97",
        savings: "$60",
        code: "PAYLESS",
        validUntil: "25 במרץ 2026",
        countdown: new Date("2026-03-25T04:00:00"),
        usageLimit: "2 שימושים",
        isHot: !0,
        isExclusive: !0,
        features: ["38% הנחה על מסלול Rapid 50K", "$97 במקום $157", "לחודש הראשון בלבד", "ללקוחות חדשים וקיימים", "2 שימושים", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 62,
        title: "מבצע השקה Rapid 25K - רק $87! 🚀",
        description: "מסלול Rapid 25K במחיר השקה של $87 בלבד עם חלוקת רווחים 90/10!",
        company: "MFFU",
        discount: "20% הנחה",
        originalPrice: "$109",
        salePrice: "$87",
        savings: "$22",
        code: "PAYLESS",
        validUntil: "קבוע",
        isHot: !0,
        isExclusive: !0,
        features: ["$87 בלבד עם קוד PAYLESS", "חלוקת רווחים 90/10", "חידוש במחיר מוזל", "שימוש ללא הגבלה", "משיכות יומיות • תקרה $100K"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 107,
        title: "Rapid Extravaganza 25K - 40% הנחה - רק $65! 🎉",
        description: "מבצע Rapid Extravaganza! 40% הנחה על מסלול Rapid 25K - רק $65 במקום $109. חלוקת רווחים 90/10 ופוטנציאל למשיכות יומיות.",
        company: "MFFU",
        discount: "40% הנחה",
        originalPrice: "$109",
        salePrice: "$65",
        savings: "$44",
        code: "PAYLESS",
        validUntil: "23 במאי 2026",
        countdown: new Date("2026-05-23T04:00:00"),
        usageLimit: "3 שימושים",
        isHot: !0,
        isExclusive: !0,
        features: ["40% הנחה על Rapid 25K", "$65 במקום $109", "חלוקת רווחים 90/10", "פוטנציאל למשיכות יומיות", "3 שימושים", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 31,
        title: "מסלול Rapid 20% הנחה",
        description: "20% הנחה על מסלול Rapid - לאיפוסים או רכישות חדשות",
        company: "MFFU",
        discount: "20% הנחה",
        code: "PAYLESS",
        validUntil: "ללא תוקף",
        usageLimit: "3 שימושים",
        isExclusive: !0,
        features: ["20% הנחה על מסלול Rapid", "לאיפוסים או רכישות חדשות", "עד 3 שימושים", "הון עד $150K"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 102,
        title: "Flex 25K - 20% הנחה - $76 במקום $95",
        description: "20% הנחה קבועה על מסלול Flex 25K. ההנחה חלה גם על איפוסים ועל חידוש החשבון, ללא הגבלת שימושים.",
        company: "MFFU",
        discount: "20% הנחה",
        originalPrice: "$95",
        salePrice: "$76",
        savings: "$19",
        code: "PAYLESS",
        validUntil: "ללא תוקף",
        isExclusive: !0,
        features: ["20% הנחה קבועה על Flex 25K", "$76 במקום $95", "ללא הגבלת שימושים", "ההנחה חלה גם על איפוסים", "חלה גם על מחיר החידוש", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 103,
        title: "Flex 50K - 20% הנחה - $122.40 במקום $153",
        description: "20% הנחה קבועה על מסלול Flex 50K. ההנחה חלה גם על איפוסים ועל חידוש החשבון, ללא הגבלת שימושים.",
        company: "MFFU",
        discount: "20% הנחה",
        originalPrice: "$153",
        salePrice: "$122.40",
        savings: "$30.60",
        code: "PAYLESS",
        validUntil: "ללא תוקף",
        isExclusive: !0,
        features: ["20% הנחה קבועה על Flex 50K", "$122.40 במקום $153", "ללא הגבלת שימושים", "ההנחה חלה גם על איפוסים", "חלה גם על מחיר החידוש", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 45,
        title: "מצטרפים חדשים - 5% הנחה Flex / Rapid",
        description: "5% הנחה למצטרפים חדשים על מסלולי Flex ו-Rapid",
        company: "MFFU",
        discount: "5% הנחה",
        code: "PAYLESS",
        validUntil: "ללא תוקף",
        usageLimit: "שימוש חד פעמי",
        isExclusive: !0,
        features: ["5% הנחה למצטרפים חדשים", "מסלולי Flex / Rapid", "שימוש חד פעמי בלבד", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 46,
        title: "מצטרפים חדשים - 50% הנחה Pro! 🔥",
        description: "50% הנחה למצטרפים חדשים על מסלול Pro",
        company: "MFFU",
        discount: "50% הנחה",
        code: "PAYLESS",
        validUntil: "ללא תוקף",
        usageLimit: "שימוש חד פעמי",
        isHot: !0,
        isExclusive: !0,
        features: ["50% הנחה למצטרפים חדשים", "מסלול Pro בלבד", "שימוש חד פעמי בלבד", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 4,
        title: "40% הנחה על כל המבחנים + ללא דמי הפעלה",
        description: "40% הנחה על כל המבחנים + ביטול דמי הפעלה עם הקוד NOFEE40",
        company: "TPT",
        discount: "40% הנחה",
        code: "NOFEE40",
        validUntil: "ללא תוקף",
        isHot: !0,
        isExclusive: !0,
        features: ["40% הנחה על כל מבחן", "ללא דמי הפעלה", "אין סטופ יומי", "הון עד $150K"],
        affiliateLink: "https://takeprofittrader.com/"
    }, {
        id: 5,
        title: "דמי הפעלה בחינם 🔥",
        description: "קרדיט הפעלה בחינם בשווי $130 לתיק PRO",
        company: "TPT",
        discount: "100% הנחה",
        originalPrice: "$130",
        salePrice: "$0",
        savings: "$130",
        code: "NOFEE40",
        validUntil: "ללא תוקף",
        isHot: !0,
        isExclusive: !0,
        features: ["דמי הפעלה בחינם ($130)", "קרדיט עד 10:00 שעון ישראל", "לאחר מעבר מבחן מוצלח", "רכישת תיק PRO בחינם"],
        affiliateLink: "https://takeprofittrader.com/"
    }, {
        id: 6,
        title: "מבצע בלעדי - ניסיון חינם",
        description: "7 ימי ניסיון בחינם + 10% הנחה על החודש הראשון!",
        company: "TradeSyncer",
        discount: "10% הנחה + ניסיון חינם",
        code: "PAYLESS",
        validUntil: "ללא תוקף",
        isExclusive: !0,
        features: ["7 ימי ניסיון בחינם", "10% הנחה על החודש הראשון", "קוד PAYLESS", "העתקת עסקאות אוטומטית"],
        affiliateLink: "https://app.tradesyncer.com/?ref=TS6BAB4CF4"
    }, {
        id: 10,
        title: "מצטרפים חדשים - 15$ מתנה 🔥",
        description: "15$ מתנה לרכישת מנוי מועדף למערכת",
        company: "TradingView",
        discount: "15$ מתנה",
        originalPrice: "$0",
        salePrice: "$15 מתנה",
        savings: "$15",
        validUntil: "ללא תוקף",
        isHot: !0,
        isExclusive: !0,
        features: ["15$ מתנה", "למצטרפים חדשים בלבד", "לרכישת מנוי מועדף", "פלטפורמת ניתוח מתקדמת"],
        affiliateLink: "https://il.tradingview.com/?share_your_love=sbuzaglo_trader"
    }, {
        id: 9,
        title: "BLACK FRIDAY 🔥",
        description: "עד 80% הנחה + חודש חינם על כל התוכניות - מסתיים ב-29.11 בשעה 10:00!",
        company: "TradingView",
        discount: "עד 80% הנחה + חודש חינם",
        validUntil: "29 בנובמבר 10:00",
        countdown: new Date("2025-11-29T10:00:00"),
        isHot: !0,
        isExclusive: !0,
        features: ["עד 80% הנחה", "חודש חינם על כל התוכניות", "הרחבת זמן למנויים קיימים", "זיכוי יחסי לשדרוגים"],
        affiliateLink: "https://il.tradingview.com/?aff_id=144619"
    }, {
        id: 14,
        title: "תוסף NinjaTrader - 20% הנחה",
        description: "20% הנחה על כל חבילות Replikanto - תוסף העתקת עסקאות הטוב ביותר ל-NinjaTrader 8",
        company: "Replikanto",
        discount: "20% הנחה",
        code: "PAYLESS",
        validUntil: "ללא תוקף",
        isHot: !1,
        isExclusive: !0,
        features: ["20% הנחה על כל החבילות", "תוסף העתקה ל-NinjaTrader 8", "תמיכה מלאה ב-Tradovate ו-Rithmic", "העתקה בין מחשבים שונים"],
        affiliateLink: "https://flowbots.ninja/product/replikanto/?v=4605f628f91d&wpam_id=316"
    }, {
        id: 70,
        title: "25% הנחה לכבוד חג הפסח! 🎉",
        description: "25% הנחה על כל התוכניות באלפא פיוצ'רס לכבוד חג הפסח - עד ה-6 באפריל!",
        company: "AlphaFutures",
        discount: "25% הנחה",
        code: "PAYLESS",
        validUntil: "6 באפריל 2026 00:00 (שעון לונדון)",
        countdown: new Date("2026-04-06T23:00:00Z"),
        isHot: !0,
        isExclusive: !0,
        features: ["25% הנחה על כל התוכניות", "מבצע חג הפסח 🎉", "בתוקף עד 6.4.26 בחצות (לונדון)", "קוד PAYLESS"],
        affiliateLink: "https://app.alpha-futures.com/signup/PAYLESS/"
    }, {
        id: 71,
        title: "קבלו 100$ הנחה באיפוס תיק מימון דמה במסלול זירו! 💪",
        description: "100$ הנחה על איפוסי חשבונות מוסמכים Zero - ללא צורך בקוד!",
        company: "AlphaFutures",
        discount: "$100 הנחה",
        validUntil: "10 באפריל 2026 23:59 EST",
        countdown: new Date("2026-04-11T03:59:00Z"),
        isHot: !0,
        isExclusive: !1,
        features: ["25K: 299$ → 399$", "50K: 399$ → 499$", "100K: 699$ → 799$", "ללא צורך בקוד!"],
        affiliateLink: "https://app.alpha-futures.com/signup/PAYLESS/"
    }, {
        id: 55,
        title: "25% הנחה על כל מבחני Zero! ⚡",
        description: "25% הנחה על כל מבחני Zero באלפא פיוצ'רס - חשבון 25K חדש רק $59.25!",
        company: "AlphaFutures",
        discount: "25% הנחה",
        code: "PAYLESS",
        validUntil: "12 במרץ 2026 23:59 EST",
        countdown: new Date("2026-03-13T04:59:00Z"),
        isHot: !0,
        isExclusive: !0,
        features: ["25% הנחה על כל מבחני Zero", "חשבון 25K חדש רק $59.25!", "מעבר ביום אחד (ONE DAY PASS)", "קוד PAYLESS"],
        affiliateLink: "https://app.alpha-futures.com/signup/PAYLESS/"
    }, {
        id: 27,
        title: "50K Standard + תיק חינם! 🔥",
        description: "קונים תיק 50K במסלול Standard ומקבלים 10% הנחה + תיק נוסף בחינם!",
        company: "AlphaFutures",
        discount: "10% הנחה + תיק חינם",
        code: "PAYLESS",
        validUntil: "13 בדצמבר 07:00",
        countdown: new Date("2025-12-13T07:00:00"),
        isHot: !0,
        isExclusive: !0,
        features: ["10% הנחה על תיק 50K Standard", "תיק נוסף בחינם!", "מסלול Standard בלבד", "קוד PAYLESS"],
        affiliateLink: "https://app.alpha-futures.com/signup/PAYLESS/"
    }, {
        id: 50,
        title: "מבצע סוף חודש אפריל - 20% הנחה! 🔥",
        description: "20% הנחה על כל התוכניות באלפא פיוצ'רס - ללא הגבלת שימושים!",
        company: "AlphaFutures",
        discount: "20% הנחה",
        code: "PAYLESS",
        validUntil: "1 במאי 2026 07:00 שעון ישראל",
        countdown: new Date("2026-05-01T04:00:00Z"),
        isHot: !0,
        isExclusive: !0,
        features: ["20% הנחה על כל התוכניות", "בתוקף עד 1.5.26 07:00 שעון ישראל", "קוד PAYLESS"],
        affiliateLink: "https://app.alpha-futures.com/signup/PAYLESS/"
    }, {
        id: 15,
        title: "הנחה בלעדית 10%",
        description: "10% הנחה בלעדית על כל רכישה ללא הגבלה!",
        company: "AlphaFutures",
        discount: "10% הנחה",
        code: "PAYLESS",
        validUntil: "ללא תוקף",
        isExclusive: !0,
        features: ["10% הנחה על כל החשבונות", "קוד PAYLESS", "בלעדי לקהילה"],
        affiliateLink: "https://app.alpha-futures.com/signup/PAYLESS/"
    }, {
        id: 20,
        title: "Black Friday Pro 50% הנחה 🔥",
        description: "50% הנחה על חשבונות Pro + 1 מתוך 10 משתמשים מקבלים איפוס חינם!",
        company: "MFFU",
        discount: "50% הנחה",
        originalPrice: "$227",
        salePrice: "$114",
        savings: "$113",
        code: "PAYLESS",
        validUntil: "29 בנובמבר 10:00",
        countdown: new Date("2025-11-29T10:00:00"),
        usageLimit: "3 שימושים ללקוח",
        isHot: !0,
        isExclusive: !0,
        features: ["50% הנחה על Pro 50K/100K/150K", "Pro 50K: $227 → $114", "אין כלל עקביות", "אין הגבלת הפסד יומי", "2 ימים למעבר", "משיכות מיידיות + $0 הפעלה", "1 מתוך 10 מקבלים איפוס חינם"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 22,
        title: "CYBER MONDAY 30% הנחה 🔥",
        description: "30% הנחה על תוכניות Pro + 1 מתוך 10 משתמשים זוכים באיפוס חינם!",
        company: "MFFU",
        discount: "30% הנחה",
        code: "PAYLESS",
        validUntil: "2 בדצמבר 23:59",
        countdown: new Date("2025-12-02T23:59:00"),
        isHot: !0,
        isExclusive: !0,
        features: ["30% הנחה על Pro 50K/100K/150K", "1 מתוך 10 זוכים באיפוס חינם", "קוד PAYLESS", "מבצע Cyber Monday", "בתוקף עד 2.12 בשעה 23:59"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 60,
        title: "עד 90% הנחה על כל התוכניות - Apex Trader Funding",
        description: "קוד קופון SAVENOW - עד 90% הנחה על כל התוכניות ב-Apex Trader Funding",
        company: "ApexTraderFunding",
        discount: "90% הנחה",
        code: "SAVENOW",
        validUntil: "ללא תוקף",
        isHot: !0,
        hidden: !0,
        features: ["עד 90% הנחה", "על כל התוכניות"],
        affiliateLink: "https://apextraderfunding.com/"
    }, {
        id: 61,
        title: "10% הנחה בכל רכישה - Funded Award",
        description: "פלאקים ותעודות פיזיות לסוחרים ממומנים — הנציחו את ההישגים שלכם בסטייל!",
        company: "FundedAward",
        discount: "10%",
        code: "PAYLESS",
        validUntil: "קבוע",
        isExclusive: !0,
        features: ["Funded AWARD - פלאק אקרילי", "Funded miniAWARD", "Bundle Up - חבילות משתלמות", "Gift Cards - כרטיסי מתנה"],
        affiliateLink: "https://fundedaward.com/propfirmpayless"
    }, {
        id: 65,
        title: "BOGO Elite ACCESS — 1+1 חינם! 🎁🔥",
        description: "מבצע BOGO על Elite ACCESS ב-Top One Futures: על כל חשבון שתרכוש תקבל חשבון נוסף חינם — עד 10 חשבונות פעילים בו-זמנית (במקום 5). תקף 2.6.26 — 15.6.26.",
        company: "TopOneFutures",
        discount: "1+1 חינם",
        code: "PAYLESS",
        validUntil: "עד 15.6.26",
        countdown: new Date("2026-06-15T20:59:00Z"),
        isHot: !0,
        isExclusive: !0,
        features: ["1+1 על Elite ACCESS — עד 10 חשבונות", "הערכה ב-$39 בלבד לכל הגדלים", "מימוש דרך הלינק + קוד PAYLESS"],
        affiliateLink: "https://toponefutures.com/?linkId=lp_707970&sourceId=payless&tenantId=toponefutures"
    }, {
        id: 84,
        title: "Flex — עד 40% הנחה ל-5 התיקים הראשונים ⚡",
        description: "מבצע מוגבל בזמן על מסלול Flex של FundedNext: עד 40% הנחה על 5 רכישות התיקים הראשונות. יעדי רווח נמוכים, ללא מגבלת הפסד יומי וללא דמי הפעלה. מימוש דרך הלינק שלי + קוד הקופון FLEXJU.",
        company: "FundedNext",
        discount: "40% הנחה",
        code: "FLEXJU",
        validUntil: "מוגבל בזמן",
        usageLimit: "5 רכישות ראשונות",
        isHot: !0,
        isExclusive: !0,
        features: ["עד 40% הנחה על 5 התיקים הראשונים", "ללא מגבלת הפסד יומי + ללא דמי הפעלה", "מימוש דרך הלינק + קוד FLEXJU"],
        affiliateLink: "https://fundednext.com/?fpr=shalom95"
    }, {
        id: 85,
        title: "Flex — עד 32% הנחה מהרכישה השישית והלאה 🔥",
        description: "ממשיכים לחסוך: עד 32% הנחה על מסלול Flex של FundedNext מהרכישה השישית והלאה, ללא הגבלת מספר שימושים. מימוש דרך הלינק שלי + קוד הקופון FLEXJU.",
        company: "FundedNext",
        discount: "32% הנחה",
        code: "FLEXJU",
        validUntil: "מוגבל בזמן",
        usageLimit: "מהרכישה השישית והלאה",
        isHot: !0,
        features: ["עד 32% הנחה מהרכישה השישית והלאה", "ללא מגבלת הפסד יומי + ללא דמי הפעלה", "מימוש דרך הלינק + קוד FLEXJU"],
        affiliateLink: "https://fundednext.com/?fpr=shalom95"
    }, {
        id: 66,
        title: "🎁 1+1 על חשבונות Futures — FundedNext",
        description: "קנו חשבון Futures אחד וקבלו שני חינם! חל על כל מסלולי ה-Futures, ללא הגבלת רכישות (עד תקרת ההקצאה). החשבון החינמי מונפק לאחר המשיכה הראשונה. לא חל על Resets.",
        company: "FundedNext",
        discount: "1+1 חינם",
        code: "FAST50",
        validUntil: "08.05.2026",
        countdown: new Date("2026-05-08T20:59:00Z"),
        isHot: !0,
        features: ["חל על כל מסלולי ה-Futures", "החשבון החינמי לאחר המשיכה הראשונה", "ללא הגבלת רכישות עד תקרת ההקצאה"],
        affiliateLink: "https://fundednext.com/?fpr=shalom95"
    }, {
        id: 124,
        title: "BOLT 50K — רק $79.99 (במקום $99.99)! ⚡",
        description: "מבצע על תיקי BOLT 50K של FundedNext: $79.99 בלבד במקום $99.99 עם הקוד GET20. ללא הגבלת שימושים. לא תקף על איפוסים (Resets).",
        company: "FundedNext",
        discount: "20% הנחה",
        code: "GET20",
        originalPrice: "$99.99",
        salePrice: "$79.99",
        savings: "$20",
        validUntil: "ללא הגבלת זמן",
        isHot: !0,
        features: ["תיקי BOLT 50K — $79.99 בלבד", "ללא הגבלת שימושים", "לא תקף על איפוסים (Resets)"],
        affiliateLink: "https://fundednext.com/?fpr=shalom95"
    }, {
        id: 73,
        title: "מסלול Builder — 40% הנחה לחודש הראשון 🏗️🔥",
        description: "40% הנחה על מסלול Builder ב-MFFU! Default: $92 | Lower MLL: $75. עד 3 שימושים — המבצע הוארך עד סוף יוני 2026.",
        company: "MFFU",
        discount: "40% הנחה",
        code: "PAYLESS",
        validUntil: "עד 30.6.26 בשעה 23:00",
        countdown: new Date("2026-06-30T20:00:00Z"),
        usageLimit: "עד 3 שימושים",
        isHot: !0,
        isExclusive: !0,
        features: ["40% הנחה — עד 3 שימושים", "30% הנחה על כל הרכישות הבאות", "מעבר אתגר אפילו ביום אחד", "משיכות אפשריות כל 48 שעות", "Default $92 • Lower MLL $75", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 72,
        title: "מסלול Builder — 30% הנחה קבועה 🏗️",
        description: "30% הנחה קבועה על מסלול Builder ב-MFFU! Default: $107 | Lower MLL: $87. ללא הגבלת שימושים.",
        company: "MFFU",
        discount: "30% הנחה",
        code: "PAYLESS",
        validUntil: "ללא תוקף",
        isHot: !0,
        isExclusive: !0,
        features: ["30% הנחה — לכל הרכישות לאחר 3 השימושים", "Default $107 • Lower MLL $87", "מעבר אתגר אפילו ביום אחד", "משיכות אפשריות כל 48 שעות", "שימוש חוזר ללא הגבלה", "קוד PAYLESS"],
        affiliateLink: "https://myfundedfutures.com/challenge?ref=4109&code=payless"
    }, {
        id: 110,
        title: "Elite Daily — 50% הנחה ⚡🔥",
        description: "50% OFF Elite Daily Accounts! 50% הנחה על חשבונות Elite Daily ב-Top One Futures דרך הלינק שלי + קוד PAYLESS. ללא הגבלת שימושים — תקף לכל חודש יוני 2026.",
        company: "TopOneFutures",
        discount: "50%",
        code: "PAYLESS",
        validUntil: "30 ביוני 2026",
        countdown: new Date("2026-06-30T20:59:00Z"),
        usageLimit: "ללא הגבלה",
        isHot: !0,
        isExclusive: !0,
        features: ["50% הנחה על חשבונות Elite Daily", "ללא הגבלת שימושים — תקף עד 30.6.26", "מימוש דרך הלינק + קוד PAYLESS"],
        affiliateLink: "https://toponefutures.com/?linkId=lp_707970&sourceId=payless&tenantId=toponefutures"
    }, {
        id: 87,
        title: "Instant Sim Funded — 50% הנחה! ⚡",
        description: "50% הנחה על כל תיקי Instant Sim Funded ב-Top One Futures עם הקוד PAYLESS. מימוש דרך הלינק שלי + קוד הקופון. ללא הגבלת שימושים — תקף לכל חודש יוני 2026.",
        company: "TopOneFutures",
        discount: "50%",
        code: "PAYLESS",
        validUntil: "30 ביוני 2026",
        countdown: new Date("2026-06-30T20:59:00Z"),
        usageLimit: "ללא הגבלה",
        isHot: !0,
        isExclusive: !0,
        features: ["50% הנחה על כל תיקי Instant Sim Funded", "ללא הגבלת שימושים — עד 30.6.26", "מימוש דרך הלינק + קוד PAYLESS"],
        affiliateLink: "https://toponefutures.com/?linkId=lp_707970&sourceId=payless&tenantId=toponefutures"
    }, {
        id: 63,
        title: "40% הנחה בלעדית — TOF",
        description: "40% הנחה בלעדית על כל מסלולי TOF עם הקוד PAYLESS",
        company: "TopOneFutures",
        discount: "40%",
        code: "PAYLESS",
        validUntil: "קבוע",
        isExclusive: !0,
        features: ["כל המסלולים — Instant, Ignite, Elite ACCESS, Elite Daily", "מימון עד $750,000 • 90% רווחים", "ללא דמי דאטה חודשיים"],
        affiliateLink: "https://toponefutures.com/?linkId=lp_707970&sourceId=payless&tenantId=toponefutures"
    }, {
        id: 80,
        title: "FFF Velocity - 80% הנחה! ⚡🔥",
        description: "80% הנחה על מסלול VELOCITY ב-Funded Futures Family — תקף ל-5 השימושים הראשונים.",
        company: "FundedFuturesFamily",
        discount: "80%",
        code: "PAYLESS",
        validUntil: "30 ביוני 2026",
        countdown: new Date("2026-06-30T20:59:00Z"),
        usageLimit: "5 שימושים ראשונים",
        isHot: !0,
        isExclusive: !0,
        features: ["80% הנחה על VELOCITY", "תקף ל-5 שימושים ראשונים", "כולל מבחן ואיפוסים"],
        affiliateLink: "https://app.fundedfuturesfamily.com/affiliation/?ref_code=05f30ffb-cec1-45be-b6f5-54fbffb022d2"
    }, {
        id: 122,
        title: "FFF Velocity - 70% הנחה (לאחר 5 שימושים) ⚡",
        description: "70% הנחה על VELOCITY ב-FFF לאחר ניצול 5 השימושים הראשונים — ללא הגבלת שימושים.",
        company: "FundedFuturesFamily",
        discount: "70%",
        code: "PAYLESS",
        validUntil: "30 ביוני 2026",
        countdown: new Date("2026-06-30T20:59:00Z"),
        usageLimit: "ללא הגבלה (לאחר 5 שימושים ראשונים)",
        isExclusive: !0,
        features: ["70% הנחה על VELOCITY", "לאחר ניצול 5 השימושים הראשונים", "ללא הגבלת שימושים"],
        affiliateLink: "https://app.fundedfuturesfamily.com/affiliation/?ref_code=05f30ffb-cec1-45be-b6f5-54fbffb022d2"
    }, {
        id: 81,
        title: "FFF Premier - 40% הנחה 🛡️",
        description: "40% הנחה על מסלול PREMIER ב-FFF — תקף ל-5 השימושים הראשונים.",
        company: "FundedFuturesFamily",
        discount: "40%",
        code: "PAYLESS",
        validUntil: "30 ביוני 2026",
        countdown: new Date("2026-06-30T20:59:00Z"),
        usageLimit: "5 שימושים ראשונים",
        isHot: !0,
        isExclusive: !0,
        features: ["40% הנחה על PREMIER", "תקף ל-5 שימושים ראשונים", "תקף למבחן ולאיפוסים"],
        affiliateLink: "https://app.fundedfuturesfamily.com/affiliation/?ref_code=05f30ffb-cec1-45be-b6f5-54fbffb022d2"
    }, {
        id: 123,
        title: "FFF Premier - 30% הנחה (לאחר 5 שימושים) 🛡️",
        description: "30% הנחה על PREMIER ב-FFF לאחר ניצול 5 השימושים הראשונים — ללא הגבלת שימושים.",
        company: "FundedFuturesFamily",
        discount: "30%",
        code: "PAYLESS",
        validUntil: "30 ביוני 2026",
        countdown: new Date("2026-06-30T20:59:00Z"),
        usageLimit: "ללא הגבלה (לאחר 5 שימושים ראשונים)",
        isExclusive: !0,
        features: ["30% הנחה על PREMIER", "לאחר ניצול 5 השימושים הראשונים", "ללא הגבלת שימושים"],
        affiliateLink: "https://app.fundedfuturesfamily.com/affiliation/?ref_code=05f30ffb-cec1-45be-b6f5-54fbffb022d2"
    }, {
        id: 82,
        title: "FFF Prime - 30% הנחה לכל חודש יוני ✨",
        description: "30% הנחה על מסלול PRIME ב-FFF — לאורך כל חודש יוני 2026.",
        company: "FundedFuturesFamily",
        discount: "30%",
        code: "PAYLESS",
        validUntil: "30 ביוני 2026",
        countdown: new Date("2026-06-30T20:59:00Z"),
        usageLimit: "ללא הגבלה לאורך חודש יוני",
        isHot: !0,
        isExclusive: !0,
        features: ["30% הנחה על PRIME", "תקף לכל חודש יוני 2026", "כולל מבחן ואיפוסים"],
        affiliateLink: "https://app.fundedfuturesfamily.com/affiliation/?ref_code=05f30ffb-cec1-45be-b6f5-54fbffb022d2"
    }, {
        id: 83,
        title: "TradeZella - 20% הנחה למצטרפים חדשים 📊",
        description: "20% הנחה למצטרפים חדשים בלבד על התשלום הראשון ביומן המסחר המתקדם TradeZella - נתח ביצועים, בנה Playbooks ושפר את המסחר שלך.",
        company: "TradeZella",
        discount: "20% הנחה",
        code: "PAYLESS",
        validUntil: "מבצע בלעדי קבוע",
        usageLimit: "למצטרפים חדשים בלבד",
        isExclusive: !0,
        features: ["20% הנחה על התשלום הראשון", "למצטרפים חדשים בלבד", "תקף לכל המסלולים (Basic / Premium)", "קוד PAYLESS"],
        affiliateLink: "https://refer.tradezella.com/payless"
    }, {
        id: 100,
        title: "החזר עמלות עד $50 — אינטראקטיב ישראל 💸",
        description: "פתחו חשבון מסחר באינטראקטיב ישראל (IBKR) דרך PAYLESS וקבלו החזר עמלות מסחר של עד $50. נציגות ישראלית רשמית עם תמיכה וייעוץ בעברית.",
        company: "InteractiveBrokers",
        discount: "עד $50 החזר",
        validUntil: "ללא תוקף",
        isExclusive: !0,
        features: ["נציגות ישראלית רשמית של IBKR", "החזר עמלות מסחר עד $50", "תמיכה וייעוץ בעברית"],
        affiliateLink: "https://lp3.inter-il.com/ab/788"
    }, {
        id: 101,
        title: "AC Holding — שיחת התאמה אישית ללא עלות 🤝",
        description: "פגישת ייעוץ והתאמת אסטרטגיית השקעה עם צוות AC Holding, ללא עלות וללא התחייבות.",
        company: "AcHolding",
        discount: "ייעוץ חינם",
        validUntil: "ללא תוקף",
        isExclusive: !0,
        features: ["שיחת ייעוץ אישית 1-on-1", "אבחון צרכי השקעה", "ללא עלות וללא התחייבות"],
        affiliateLink: "https://propfirmpayless.com/services/ac-holding#lead-form"
    }]